name: Deploy Static Website to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'github-pages-deployment/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Create .nojekyll file
        run: touch github-pages-deployment/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'github-pages-deployment'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
